/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('primevue/dialog')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewSpaceButton: typeof import('./src/components/NewSpaceButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SpacesList: typeof import('./src/components/SpacesList.vue')['default']
  }
}
